services:
  comfyui:
    user: "1000:1000"
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8188:8188"
    volumes:
      - "./models:/app/models"
      - "./input:/app/input"
      - "./temp:/app/output/temp"
      - "./output:/app/output"
      - "./user:/app/user"
      - "./custom_venv:/app/custom_venv"
      - "./custom_nodes:/app/custom_nodes"
