services:
  comfyui:
    build: .
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]