# Disable all rules by default
lint.ignore = ["ALL"]

# Enable specific rules
lint.select = [
    "S307",  # suspicious-eval-usage
    "F401",  # unused-import
    "F841",  # unused-local-variable
    "F821",  # undefined-name
]