# generated by datamodel-codegen:
#   filename:  http://localhost:8080/openapi
#   timestamp: 2025-04-22T09:45:21+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from . import PixverseDto


class ResponseData(BaseModel):
    ErrCode: Optional[int] = None
    ErrMsg: Optional[str] = None
    Resp: Optional[PixverseDto.V2OpenAPII2VResp] = None
