# This file is automatically generated by the build process when version is
# updated in pyproject.toml.
__version__ = "0.3.66"

# This deals with workspace issues
from comfy_compatibility.workspace import auto_patch_workspace_and_restart

auto_patch_workspace_and_restart()
