# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from comfy.api.paths.api_v1_images_digest.get.operation import ApiV1ImagesDigestGet
from comfy.api.paths.api_v1_prompts.get.operation import ApiV1PromptsGet
from comfy.api.paths.api_v1_prompts.post.operation import ApiV1PromptsPost
from comfy.api.paths.prompt.get.operation import GetPrompt
from comfy.api.paths.prompt.post.operation import PostPrompt
from comfy.api.paths.extensions.get.operation import GetExtensions
from comfy.api.paths.interrupt.post.operation import PostInterrupt
from comfy.api.paths.history.get.operation import GetHistory
from comfy.api.paths.history.post.operation import PostHistory
from comfy.api.paths.queue.get.operation import GetQueue
from comfy.api.paths.queue.post.operation import PostQueue
from comfy.api.paths.upload_image.post.operation import UploadImage
from comfy.api.paths.object_info.get.operation import GetObjectInfo
from comfy.api.paths.view.get.operation import ViewImage
from comfy.api.paths.embeddings.get.operation import GetEmbeddings
from comfy.api.paths.solidus.get.operation import GetRoot


class DefaultApi(
    ApiV1ImagesDigestGet,
    ApiV1PromptsGet,
    ApiV1PromptsPost,
    GetPrompt,
    PostPrompt,
    GetExtensions,
    PostInterrupt,
    GetHistory,
    PostHistory,
    GetQueue,
    PostQueue,
    UploadImage,
    GetObjectInfo,
    ViewImage,
    GetEmbeddings,
    GetRoot,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
