# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from comfy.api.shared_imports.response_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]

from .content.application_json import schema as application_json_schema
from .headers import header_digest
from .headers import header_content_disposition
from .headers import header_location
from . import header_parameters
parameters: typing.Dict[str, typing.Type[api_client.HeaderParameterWithoutName]] = {
    'Digest': header_digest.Digest,
    'Content-Disposition': header_content_disposition.ContentDisposition,
    'Location': header_location.Location,
}


@dataclasses.dataclass(frozen=True)
class ApiResponse(api_response.ApiResponse):
    body: application_json_schema.SchemaDict
    headers: header_parameters.HeadersDict


class ResponseFor200(api_client.OpenApiResponse[ApiResponse]):
    @classmethod
    def get_response(cls, response, headers, body) -> ApiResponse:
        return ApiResponse(response=response, body=body, headers=headers)


    class ApplicationJsonMediaType(api_client.MediaType):
        schema: typing_extensions.TypeAlias = application_json_schema.Schema
    content = {
        'application/json': ApplicationJsonMediaType,
    }
    headers=parameters
    headers_schema = header_parameters.Headers
