# coding: utf-8

"""
    comfyui
    No description provided (generated by Openapi JSON Schema Generator https://github.com/openapi-json-schema-tools/openapi-json-schema-generator)  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from comfy.api.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]


from comfy.api.components.schema import queue_tuple


class QueueRunningTuple(
    typing.Tuple[
        queue_tuple.QueueTupleTuple,
        ...
    ]
):

    def __new__(cls, arg: typing.Union[QueueRunningTupleInput, QueueRunningTuple], configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return QueueRunning.validate(arg, configuration=configuration)
QueueRunningTupleInput = typing.Union[
    typing.List[
        typing.Union[
            queue_tuple.QueueTupleTupleInput,
            queue_tuple.QueueTupleTuple
        ],
    ],
    typing.Tuple[
        typing.Union[
            queue_tuple.QueueTupleTupleInput,
            queue_tuple.QueueTupleTuple
        ],
        ...
    ]
]


@dataclasses.dataclass(frozen=True)
class QueueRunning(
    schemas.Schema[schemas.immutabledict, QueueRunningTuple]
):
    types: typing.FrozenSet[typing.Type] = frozenset({tuple})
    items: typing.Type[queue_tuple.QueueTuple] = dataclasses.field(default_factory=lambda: queue_tuple.QueueTuple) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            tuple: QueueRunningTuple
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            QueueRunningTupleInput,
            QueueRunningTuple,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> QueueRunningTuple:
        return super().validate_base(
            arg,
            configuration=configuration,
        )


class QueuePendingTuple(
    typing.Tuple[
        queue_tuple.QueueTupleTuple,
        ...
    ]
):

    def __new__(cls, arg: typing.Union[QueuePendingTupleInput, QueuePendingTuple], configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return QueuePending.validate(arg, configuration=configuration)
QueuePendingTupleInput = typing.Union[
    typing.List[
        typing.Union[
            queue_tuple.QueueTupleTupleInput,
            queue_tuple.QueueTupleTuple
        ],
    ],
    typing.Tuple[
        typing.Union[
            queue_tuple.QueueTupleTupleInput,
            queue_tuple.QueueTupleTuple
        ],
        ...
    ]
]


@dataclasses.dataclass(frozen=True)
class QueuePending(
    schemas.Schema[schemas.immutabledict, QueuePendingTuple]
):
    types: typing.FrozenSet[typing.Type] = frozenset({tuple})
    items: typing.Type[queue_tuple.QueueTuple] = dataclasses.field(default_factory=lambda: queue_tuple.QueueTuple) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            tuple: QueuePendingTuple
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            QueuePendingTupleInput,
            QueuePendingTuple,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> QueuePendingTuple:
        return super().validate_base(
            arg,
            configuration=configuration,
        )
Properties = typing.TypedDict(
    'Properties',
    {
        "queue_running": typing.Type[QueueRunning],
        "queue_pending": typing.Type[QueuePending],
    }
)


class SchemaDict(schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES]):

    __required_keys__: typing.FrozenSet[str] = frozenset({
    })
    __optional_keys__: typing.FrozenSet[str] = frozenset({
        "queue_running",
        "queue_pending",
    })
    
    def __new__(
        cls,
        *,
        queue_running: typing.Union[
            QueueRunningTupleInput,
            QueueRunningTuple,
            schemas.Unset
        ] = schemas.unset,
        queue_pending: typing.Union[
            QueuePendingTupleInput,
            QueuePendingTuple,
            schemas.Unset
        ] = schemas.unset,
        configuration_: typing.Optional[schema_configuration.SchemaConfiguration] = None,
        **kwargs: schemas.INPUT_TYPES_ALL,
    ):
        arg_: typing.Dict[str, typing.Any] = {}
        for key_, val in (
            ("queue_running", queue_running),
            ("queue_pending", queue_pending),
        ):
            if isinstance(val, schemas.Unset):
                continue
            arg_[key_] = val
        arg_.update(kwargs)
        used_arg_ = typing.cast(SchemaDictInput, arg_)
        return Schema.validate(used_arg_, configuration=configuration_)
    
    @staticmethod
    def from_dict_(
        arg: typing.Union[
            SchemaDictInput,
            SchemaDict
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> SchemaDict:
        return Schema.validate(arg, configuration=configuration)
    
    @property
    def queue_running(self) -> typing.Union[QueueRunningTuple, schemas.Unset]:
        val = self.get("queue_running", schemas.unset)
        if isinstance(val, schemas.Unset):
            return val
        return typing.cast(
            QueueRunningTuple,
            val
        )
    
    @property
    def queue_pending(self) -> typing.Union[QueuePendingTuple, schemas.Unset]:
        val = self.get("queue_pending", schemas.unset)
        if isinstance(val, schemas.Unset):
            return val
        return typing.cast(
            QueuePendingTuple,
            val
        )
    
    def get_additional_property_(self, name: str) -> typing.Union[schemas.OUTPUT_BASE_TYPES, schemas.Unset]:
        schemas.raise_if_key_known(name, self.__required_keys__, self.__optional_keys__)
        return self.get(name, schemas.unset)
SchemaDictInput = typing.Mapping[str, schemas.INPUT_TYPES_ALL]


@dataclasses.dataclass(frozen=True)
class Schema(
    schemas.Schema[SchemaDict, tuple]
):
    types: typing.FrozenSet[typing.Type] = frozenset({schemas.immutabledict})
    properties: Properties = dataclasses.field(default_factory=lambda: schemas.typed_dict_to_instance(Properties)) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            schemas.immutabledict: SchemaDict
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            SchemaDictInput,
            SchemaDict,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> SchemaDict:
        return super().validate_base(
            arg,
            configuration=configuration,
        )

