# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from comfy.api.paths.api_v1_images_digest.get.operation import ApiForGet


class ApiV1ImagesDigest(
    ApiForGet,
):
    pass
