# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from comfy.api.paths.history.get.operation import ApiForGet
from comfy.api.paths.history.post.operation import ApiForPost


class History(
    ApiForGet,
    ApiForPost,
):
    pass
